name: ci-iOS

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: macos-26
    timeout-minutes: 10

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v6

      - name: Setup Xcode
        run: |
          bin/setup-xcode.sh

      - name: Build and test
        env:
          SIMULATOR_UDID: "05494B9A-CF86-44CD-8948-A1003D606E75"
          SCHEME: "CI-iOS"
          PLATFORM_DESTINATION: "platform=iOS Simulator,arch=arm64,id=${SIMULATOR_UDID}"
          TARGET_SDK: "iphonesimulator"
        run: |
          xcrun simctl boot ${SIMULATOR_UDID}
          bin/build-and-test.sh