name: ci-iOS

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: xcode-27
    timeout-minutes: 10

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v7

      - name: Setup Xcode
        run: |
          bin/setup-xcode.sh

      - name: Preboot Simulator
        env:
          SIMULATOR_RUNTIME: "27-0"
          SIMULATOR_NAME: "iPhone 17"
        run: |
          bin/preboot-simulator.sh

      - name: Build and test
        env:
          SCHEME: "CI-iOS"
          PLATFORM_DESTINATION: "platform=iOS Simulator,arch=arm64,OS=27.0,name=iPhone 17"
          TARGET_SDK: "iphonesimulator"
        run: |
          bin/build-and-test.sh

      - name: Upload test failure artifacts
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: test-failure-artifacts
          path: |
            TestResults.xcresult
            EssentialFeed/EssentialFeedMobileTests/**/FailureImages/*.png
          retention-days: 3